### ISSUE TITLE
Compile into MBIN

### ISSUE THREAD

**Issue by theFisher86** [theFisher86/No-Mans-GUI#6]
Make sure we can compile back to MBIN with what we have complete so far.  I think working on anything other than that at this point might be a bad idea b/c there's a small chance we may need to change everything in order for it to compile back to MBIN correctly.

**Comment by wannabeuk** [comment]
Working on this currently in the save-test branch, Good cool on this as i have needed to re-write the parsing to get the best result. Some solid advice from gat means this is now pretty easy to do in most cases, just need to work out how to handle all the variations of array and list.

**Comment by wannabeuk** [comment]
This "should" now be implemented. Closing the issue
